apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuel-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuel-api
  template:
    metadata:
      labels:
        app: fuel-api
    spec:
      containers:
      - name: fuel-api
        image: fuel-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fuel-api-service
spec:
  type: NodePort
  selector:
    app: fuel-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
